# Generated by Django 5.2.17 on 2026-08-10 06:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('columns', wagtail.fields.StreamField([('column', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 3: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 6: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.EmailBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 1), ('link_type', 2), ('page', 3), ('url', 4), ('anchor', 5), ('document', 6), ('email', 7), ('phone', 8), ('open_in_new_tab', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Links'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 11)]], {})})),
                ('socials', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Facebook', 'max_length': 60}), 1: ('apps.core.blocks.IconBlock', (), {'help_text': 'Iconify name, e.g. mdi:facebook', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('icon', 1), ('url', 2)]], {})})),
                ('newsletter_enabled', models.BooleanField(default=True)),
                ('newsletter_heading', models.CharField(blank=True, default='Newsletter', max_length=120)),
                ('newsletter_text', models.CharField(blank=True, max_length=250)),
                ('newsletter_placeholder', models.CharField(blank=True, default='Your email', max_length=120)),
                ('newsletter_button_label', models.CharField(blank=True, default='Join', max_length=60)),
                ('copyright_text', models.CharField(blank=True, default='© {year} Lumora Treks. All rights reserved.', help_text='{year} is replaced with the current year.', max_length=250)),
                ('secondary_text', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, max_length=40)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=40)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=40)),
                ('lead_notification_email', models.EmailField(blank=True, help_text='Default recipient for enquiry form submissions.', max_length=254)),
                ('sdk_base_url', models.URLField(blank=True, help_text='Travories SDK base URL used for SDK-sourced packages.')),
                ('booking_widget_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Integrations',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('item', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 2: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 5: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('apps.core.blocks.IconBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'default': [], 'label': 'Dropdown links', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8), ('icon', 9), ('children', 11), ('highlight', 8)]], {})}, verbose_name='Nav items')),
                ('cta_button', wagtail.fields.StreamField([('button', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 2: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 5: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 11: ('apps.core.blocks.IconBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8), ('style', 9), ('size', 10), ('icon', 11)]], {})})),
                ('sticky', models.BooleanField(default=True)),
                ('announcement_text', models.CharField(blank=True, help_text='Optional bar above the navbar.', max_length=250)),
                ('announcement_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#f5f5f5', max_length=20)),
                ('surface', models.CharField(default='#ffffff', max_length=20)),
                ('foreground', models.CharField(default='#1e1e1e', max_length=20)),
                ('primary', models.CharField(default='#68bf4d', max_length=20)),
                ('primary_hover', models.CharField(default='#59a941', max_length=20)),
                ('primary_active', models.CharField(default='#4a9036', max_length=20)),
                ('primary_accent', models.CharField(default='#8bff66', max_length=20)),
                ('secondary', models.CharField(default='#1e1e1e', max_length=20)),
                ('secondary_hover', models.CharField(default='#343434', max_length=20)),
                ('secondary_active', models.CharField(default='#050505', max_length=20)),
                ('text_primary', models.CharField(default='#1e1e1e', max_length=20)),
                ('text_secondary', models.CharField(default='#47586e', max_length=20)),
                ('text_muted', models.CharField(default='#546881', max_length=20)),
                ('text_inverse', models.CharField(default='#f5f5f5', max_length=20)),
                ('border', models.CharField(default='#e0e4e8', max_length=20)),
            ],
            options={
                'verbose_name': 'Theme colours',
            },
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lumora Treks', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('logo_icon', models.CharField(blank=True, default='ph:mountains-fill', help_text='Iconify name used when no logo image is set.', max_length=100)),
                ('default_meta_title', models.CharField(blank=True, max_length=200)),
                ('default_meta_description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('default_share_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
                ('logo_dark', models.ForeignKey(blank=True, help_text='Used on dark backgrounds (footer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'verbose_name': 'Brand & contact',
            },
        ),
    ]
