# Generated by Django 5.2.17 on 2026-09-29 06:34

import apps.core.fields
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='address',
            field=apps.core.fields.LimitedTextField(blank=True, ui_max_length=25),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='default_meta_description',
            field=apps.core.fields.LimitedTextField(blank=True, ui_max_length=160),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='default_meta_title',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=200, ui_max_length=60),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='site_name',
            field=apps.core.fields.LimitedCharField(default='Lumora Treks', max_length=120, ui_max_length=15),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='tagline',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=250, ui_max_length=30),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='columns',
            field=wagtail.fields.StreamField([('column', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'URL or site path'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 3: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 4: ('apps.core.blocks.LinkURLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 6: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.EmailBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 1), ('link_type', 2), ('page', 3), ('url', 4), ('anchor', 5), ('document', 6), ('email', 7), ('phone', 8), ('open_in_new_tab', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Links'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=apps.core.fields.LimitedCharField(blank=True, default='© {year} Lumora Treks. All rights reserved.', help_text='{year} is replaced with the current year.', max_length=250, ui_max_length=45),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='description',
            field=apps.core.fields.LimitedTextField(blank=True, ui_max_length=130),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_button_label',
            field=apps.core.fields.LimitedCharField(blank=True, default='Join', max_length=60, ui_max_length=10),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_heading',
            field=apps.core.fields.LimitedCharField(blank=True, default='Newsletter', max_length=120, ui_max_length=15),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_placeholder',
            field=apps.core.fields.LimitedCharField(blank=True, default='Your email', max_length=120, ui_max_length=15),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_text',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=250, ui_max_length=55),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='secondary_text',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=250, ui_max_length=55),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='announcement_text',
            field=apps.core.fields.LimitedCharField(blank=True, help_text='Optional bar above the navbar.', max_length=250, ui_max_length=80),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='cta_button',
            field=wagtail.fields.StreamField([('button', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'URL or site path'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 2: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 3: ('apps.core.blocks.LinkURLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 5: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 11: ('apps.core.blocks.IconBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8), ('style', 9), ('size', 10), ('icon', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'URL or site path'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 2: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 3: ('apps.core.blocks.LinkURLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 5: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('apps.core.blocks.IconBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'default': [], 'label': 'Dropdown links', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_type', 1), ('page', 2), ('url', 3), ('anchor', 4), ('document', 5), ('email', 6), ('phone', 7), ('open_in_new_tab', 8), ('icon', 9), ('children', 11), ('highlight', 8)]], {})}, verbose_name='Nav items'),
        ),
    ]
