# Generated by Django 5.2.17 on 2026-09-29 07:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_editorial_character_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='columns',
            field=wagtail.fields.StreamField([('column', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional — leave empty for a plain list of links.', 'max_length': 20, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'URL or site path'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 3: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 4: ('apps.core.blocks.LinkURLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 6: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.EmailBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 1), ('link_type', 2), ('page', 3), ('url', 4), ('anchor', 5), ('document', 6), ('email', 7), ('phone', 8), ('open_in_new_tab', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Links'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 11)]], {})}),
        ),
    ]
