# Generated by Django 5.2 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google")],
                        max_length=32,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Stable user identifier issued by the provider.",
                        max_length=255,
                    ),
                ),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "social identity",
                "verbose_name_plural": "social identities",
                "ordering": ["provider", "subject"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"),
                        name="accounts_social_provider_subject_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"),
                        name="accounts_social_user_provider_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TravelerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("USER", "User")],
                        default="USER",
                        help_text="Lumora application role; independent of Django CMS permissions.",
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                ("interests", models.JSONField(blank=True, default=list)),
                (
                    "traveler_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solo", "Solo traveler"),
                            ("couple", "Couple"),
                            ("family", "Family"),
                            ("friends", "Friends"),
                            ("group", "Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onboarding_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traveler_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "traveler profile",
                "verbose_name_plural": "traveler profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
