# Generated by Django 5.2.17 on 2026-09-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadsubmission_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'lead', 'verbose_name_plural': 'leads'},
        ),
    ]
