# Generated by Django 5.2.17 on 2026-08-10 06:50

import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, help_text='e.g. Annapurna, Everest.', max_length=120)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('default_layout', models.CharField(choices=[('small', 'Small tile'), ('tall', 'Tall tile'), ('wide', 'Wide tile'), ('large', 'Large feature tile')], default='small', max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short line shown on the card.')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(blank=True, help_text='e.g. 4 days & 3 nights', max_length=120)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('people_count', models.PositiveIntegerField(default=1, help_text='Max group size.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenuous', 'Strenuous')], max_length=40)),
                ('includes', models.TextField(blank=True, help_text='One item per line.')),
                ('excludes', models.TextField(blank=True, help_text='One item per line.')),
                ('is_popular', models.BooleanField(default=False, help_text='Shown in the Popular Packages carousel.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('cms', 'Authored in the CMS'), ('sdk', 'Mirrored from the Travories SDK')], default='cms', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='Package id in the company SDK, when this entry mirrors an SDK package.', max_length=120)),
                ('booking_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PackageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Iconify name.', max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day_label', models.CharField(blank=True, help_text='e.g. Day 1 — defaults to position.', max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(blank=True, help_text='e.g. Everest Base Camp Trekker', max_length=160)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
