# Generated by Django 5.2.17 on 2026-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Trekking', 'Trekking'), ('Sightseeing', 'Sightseeing'), ('Paragliding', 'Paragliding')], default='Trekking', help_text='Drives the /packages page filter tabs.', max_length=40),
        ),
    ]
