# Generated by Django 5.2.17 on 2026-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_package_category'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'is_popular', 'sort_order'], name='catalog_pac_is_acti_6e1162_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='catalog_pac_categor_3a94a2_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['destination', 'is_active'], name='catalog_pac_destina_b5ece1_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['package', 'sort_order'], name='catalog_tes_package_92d674_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['package', 'rating'], name='catalog_tes_package_e25ad0_idx'),
        ),
    ]
