# Generated by Django 5.2.17 on 2026-08-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_package_catalog_pac_is_acti_6e1162_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('one_star', models.PositiveIntegerField(default=0)),
                ('two_star', models.PositiveIntegerField(default=0)),
                ('three_star', models.PositiveIntegerField(default=0)),
                ('four_star', models.PositiveIntegerField(default=0)),
                ('five_star', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to='catalog.package')),
            ],
            options={
                'indexes': [models.Index(fields=['average_rating', 'total_reviews'], name='catalog_pac_average_eba036_idx')],
            },
        ),
    ]
