# Generated by Django 5.2.17 on 2026-08-12 11:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_packageratingsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded')], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('package', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='catalog.package')),
            ],
            options={
                'ordering': ['kind', 'sort_order'],
            },
        ),
    ]
