# Generated by Django 5.2.17 on 2026-09-13 05:17

from django.db import migrations, models


def reset_unrated_packages(apps, schema_editor):
    Package = apps.get_model("catalog", "Package")
    Package.objects.filter(review_count=0).update(rating=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_destination_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.RunPython(reset_unrated_packages, migrations.RunPython.noop),
    ]
