# Generated by Django 5.2.17 on 2026-09-13 05:36

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_package_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGroupPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('min_people', models.PositiveIntegerField(help_text='Smallest group size eligible for this price.', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_people', models.PositiveIntegerField(blank=True, help_text='Largest eligible group size. Leave blank for no upper limit.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('package', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_pricing', to='catalog.package')),
            ],
            options={
                'ordering': ['sort_order', 'min_people'],
            },
        ),
    ]
