# Generated by Django 5.2.17 on 2026-09-13 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_packagegroupprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegroupprice',
            name='price_per_person',
            field=models.PositiveIntegerField(help_text='Whole-number price per person; do not enter decimals.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
