# Generated by Django 5.2.17 on 2026-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_packagegroupprice_price_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Trekking', 'Trekking'), ('Trail Run', 'Trail Run'), ('Hiking', 'Hiking'), ('Day Excursions', 'Day Excursions'), ('Religious Tour', 'Religious Tour'), ("Nepal's Wild Life", "Nepal's Wild Life"), ('6000m Peak Climbing', '6000m Peak Climbing'), ('Sightseeing', 'Sightseeing'), ('Paragliding', 'Paragliding')], default='Trekking', help_text='Drives the /packages page filter tabs.', max_length=40),
        ),
    ]
