# Generated by Django 5.2.17 on 2026-09-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_backfill_included_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='package',
            name='excludes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes',
        ),
        migrations.AlterField(
            model_name='destination',
            name='external_url',
            field=models.URLField(blank=True, help_text='Only used when this destination has no destination page of its own.'),
        ),
    ]
