# Generated by Django 5.2.17 on 2026-09-29 06:34

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_package_trip_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=120, ui_max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=apps.core.fields.LimitedCharField(blank=True, help_text='e.g. Annapurna, Everest.', max_length=120, ui_max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subtitle',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=200, ui_max_length=80),
        ),
        migrations.AlterField(
            model_name='destination',
            name='title',
            field=apps.core.fields.LimitedCharField(max_length=200, ui_max_length=25),
        ),
        migrations.AlterField(
            model_name='package',
            name='accommodation',
            field=apps.core.fields.LimitedCharField(help_text='Where travellers sleep, e.g. "Mountain teahouses (twin share)".', max_length=200, ui_max_length=40),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=apps.core.fields.LimitedCharField(blank=True, help_text='e.g. 4 days & 3 nights', max_length=120, ui_max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='meals',
            field=apps.core.fields.LimitedCharField(help_text='Which meals are covered, e.g. "Daily breakfast".', max_length=200, ui_max_length=60),
        ),
        migrations.AlterField(
            model_name='package',
            name='summary',
            field=apps.core.fields.LimitedTextField(help_text='One or two sentences shown on package cards.', ui_max_length=95),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=apps.core.fields.LimitedCharField(max_length=200, ui_max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='transport',
            field=apps.core.fields.LimitedCharField(help_text='How travellers get around, e.g. "Private jeep to the trailhead".', max_length=200, ui_max_length=50),
        ),
        migrations.AlterField(
            model_name='packagegalleryimage',
            name='caption',
            field=apps.core.fields.LimitedCharField(blank=True, max_length=255, ui_max_length=40),
        ),
        migrations.AlterField(
            model_name='packagehighlight',
            name='text',
            field=apps.core.fields.LimitedCharField(max_length=255, ui_max_length=45),
        ),
        migrations.AlterField(
            model_name='packageincludeditem',
            name='text',
            field=apps.core.fields.LimitedCharField(max_length=255, ui_max_length=35),
        ),
        migrations.AlterField(
            model_name='packageitineraryday',
            name='day_label',
            field=apps.core.fields.LimitedCharField(blank=True, help_text='e.g. Day 1 — defaults to position.', max_length=60, ui_max_length=10),
        ),
        migrations.AlterField(
            model_name='packageitineraryday',
            name='title',
            field=apps.core.fields.LimitedCharField(max_length=200, ui_max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=apps.core.fields.LimitedCharField(max_length=120, ui_max_length=15),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_role',
            field=apps.core.fields.LimitedCharField(blank=True, help_text='e.g. Everest Base Camp Trekker', max_length=160, ui_max_length=30),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=apps.core.fields.LimitedTextField(ui_max_length=155),
        ),
    ]
