# Generated by Django 5.2.17 on 2026-09-13 10:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_contactpage_privacypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('destination_header', 6), ('destination_overview', 6), ('destination_packages', 6), ('cta_banner', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Adds an id to the section so nav links like #packages can target it.', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Page background'), ('surface', 'Surface (white)'), ('dark', 'Dark (secondary)'), ('primary', 'Brand green')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default (max-w-7xl)'), ('narrow', 'Narrow'), ('full', 'Full bleed')]}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Keep the section in the page but stop rendering it.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('background', 1), ('spacing', 2), ('container', 3), ('hidden', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('settings', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Word/phrase inside heading to accent (italic, green).', 'max_length': 60, 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('apps.core.blocks.APIImageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 13: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 16: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.EmailBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 22: ('apps.core.blocks.IconBlock', (), {}), 23: ('wagtail.blocks.StructBlock', [[('label', 11), ('link_type', 12), ('page', 13), ('url', 14), ('anchor', 15), ('document', 16), ('email', 17), ('phone', 18), ('open_in_new_tab', 19), ('style', 20), ('size', 21), ('icon', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': [], 'max_num': 3, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('heading', 7), ('heading_highlight', 8), ('text', 9), ('background_image', 10), ('buttons', 24), ('settings', 5)]], {})}),
        ),
    ]
