# Generated by Django 5.2.17 on 2026-09-13 10:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_destinationdetailpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetailpage',
            name='body',
            field=wagtail.fields.StreamField([('package_header', 6), ('package_overview', 6), ('package_booking', 8), ('package_itinerary', 6), ('package_reviews', 6), ('cta_banner', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Adds an id to the section so nav links like #packages can target it.', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Page background'), ('surface', 'Surface (white)'), ('dark', 'Dark (secondary)'), ('primary', 'Brand green')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default (max-w-7xl)'), ('narrow', 'Narrow'), ('full', 'Full bleed')]}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Keep the section in the page but stop rendering it.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('background', 1), ('spacing', 2), ('container', 3), ('hidden', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('settings', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('reserve_href', 7), ('settings', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Word/phrase inside heading to accent (italic, green).', 'max_length': 60, 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': False}), 12: ('apps.core.blocks.APIImageChooserBlock', (), {'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 15: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 18: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.EmailBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 21: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 24: ('apps.core.blocks.IconBlock', (), {}), 25: ('wagtail.blocks.StructBlock', [[('label', 13), ('link_type', 14), ('page', 15), ('url', 16), ('anchor', 17), ('document', 18), ('email', 19), ('phone', 20), ('open_in_new_tab', 21), ('style', 22), ('size', 23), ('icon', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'default': [], 'max_num': 3, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 9), ('heading_highlight', 10), ('text', 11), ('background_image', 12), ('buttons', 26), ('settings', 5)]], {})}),
        ),
    ]
