# Generated by Django 5.2.17 on 2026-09-13 10:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_packagedetailpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('blog_article_header', 6), ('blog_article_body', 6), ('blog_related_stories', 9), ('cta_banner', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Adds an id to the section so nav links like #packages can target it.', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Page background'), ('surface', 'Surface (white)'), ('dark', 'Dark (secondary)'), ('primary', 'Brand green')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default (max-w-7xl)'), ('narrow', 'Narrow'), ('full', 'Full bleed')]}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Keep the section in the page but stop rendering it.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('background', 1), ('spacing', 2), ('container', 3), ('hidden', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('settings', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Keep reading', 'max_length': 120}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'max_value': 6, 'min_value': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('count', 8), ('settings', 5)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Word/phrase inside heading to accent (italic, green).', 'max_length': 60, 'required': False}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('apps.core.blocks.APIImageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'CMS page'), ('url', 'External URL'), ('anchor', 'Anchor on this page'), ('document', 'Document'), ('email', 'Email address'), ('phone', 'Phone number')]}), 16: ('apps.core.blocks.APIPageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Without the '#'.", 'max_length': 80, 'required': False}), 19: ('apps.core.blocks.APIDocumentChooserBlock', (), {'required': False}), 20: ('wagtail.blocks.EmailBlock', (), {'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 22: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 25: ('apps.core.blocks.IconBlock', (), {}), 26: ('wagtail.blocks.StructBlock', [[('label', 14), ('link_type', 15), ('page', 16), ('url', 17), ('anchor', 18), ('document', 19), ('email', 20), ('phone', 21), ('open_in_new_tab', 22), ('style', 23), ('size', 24), ('icon', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'default': [], 'max_num': 3, 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('heading', 10), ('heading_highlight', 11), ('text', 12), ('background_image', 13), ('buttons', 27), ('settings', 5)]], {})}),
        ),
    ]
